# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/librarydb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.h2.console.enabled=false
logging.level.com.library=INFO
logging.level.org.hibernate.SQL=WARN
# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never

